Math Magicians: tests
Christianib003/Math-Magician pull request #6
Opened 2022-06-02 13:09 UTC by myelin0

## In this branch:

- We set up React Testing Library
- Write unit tests for the files operate.js and calculate.js using Jest.
- Create unit tests for all React components.
- Run full tests suite using Jest. All tests should pass.
- Pass Linters.

2022-06-02 15:23 UTC, Emmyn5600 requested changes
Hi @myelin0  and @Christianib003 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
- Check the comment under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 15:23 UTC, Emmyn5600 commented on src/logic/solve.test.js
> +});
- [ ]  Please implement the following tests too, to cover all the features added in the project:

- It should give the percentage of the given number
- It should not calculate if the second operand doesn't exist.
- It should change the sign if clicked on a different sign.
- It should clear the display screen if clicked on the AC button.

2022-06-02 15:23 UTC, Emmyn5600 commented on src/logic/operation.test.js
> +});
- [ ] Please implement the following tests too, to cover all the features added in the project:

 - It should throw 0 errors if trying to make a zero division.
 - It should return 20. as next if the button name is.
 - It should give the percentage of the first operand if the button name is %.

2022-06-03 11:09 UTC, Cathella approved these changes
## 🔥 Status: Approved 🟢

### Hi @myelin0, @Christianib003 👋🏻, 

Good job making the requested changes 💪🏻!
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

✅ All tests pass 👍🏻 

Cheers and Happy coding!👏👏👏

![you-did-it-good-job](https://user-images.githubusercontent.com/4247740/171841862-057a32ed-a8d0-43fd-8fff-f382a05c4fc7.gif)


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 14:04 UTC, merged